Feature/118 relacion pet breed specie
proyecto-final-dh/backend pull request #22
Opened 2023-11-03 14:03 UTC by javtr

* se agregan las siguientes relaciones:
* pet con (user,breed,location)
* history con (pet,user)

2023-11-03 16:31 UTC, celfiew commented on src/main/java/com/company/model/entity/Pets.java
> +    private Location location;
Javi, la relación de localización se planteó en una discución que tuvimos para que la mascota tuviera la misma ubicación del usuario.

2023-11-03 16:47 UTC, celfiew requested changes
Javi Pet tiene una location a travez de user, puedes eliminar esta relación directa entre pet y localización?

Ya si luego queremos saber la location de una pet, eso lo hacemos con un metodo que ejecute una query con joins entre pet, user details y locations, eso lo va a realizar Nata.

2023-11-03 20:49 UTC, javtr commented
* retiro relación pet-location
* también debe eliminarse de la bd

![imagen](https://github.com/proyecto-final-dh/backend/assets/92610538/dff91ae1-da76-4d09-bb9f-b2d2033a4535)

2023-11-03 23:29 UTC, nataliehelm approved these changes

2023-11-03 23:29 UTC, nataliehelm commented on src/main/java/com/company/model/entity/Pets.java
> +    @ManyToOne
entiendo que la mascota se debia relacionar con location a través del usuario y no con una clave foranea. Habría que revisar y concensuar de nuevo entre todos

2023-11-04 01:11 UTC, celfiew approved these changes

2023-11-04 01:19 UTC, merged