[FEATURE] [123] - Save pet images
proyecto-final-dh/backend pull request #23
Opened 2023-11-04 19:32 UTC by ezesafdie

Se agrega la funcionalidad de subir imagenes al bucket s3. Consideraciones a tener en cuenta:

- Se modifica la base de datos (con lo nuevo de user details)
- En base al punto anterior, se modifican tambien los test relacionados a usuario para que funcionen correctamente
- Al usar keys y secrets para el bucket hay que configurar variables de entorno en el ide

Curl de prueba:
```
curl --location --request POST 'localhost:8081/storage/uploadFile'
```

Para poder mandar una imagen, hay que configurar el postman de la siguiente manera:
![image](https://github.com/proyecto-final-dh/backend/assets/69767459/b425a037-dc25-48fa-afbb-00e6fba6e01b)

2023-11-07 22:31 UTC, celfiew requested changes
Todo esto en: src/main/java/com/company/service/BucketImageService.java

Como se setearon las variables de entorno en EC2:

En el código, puedes quitar las siguientes líneas, ya que ahora las credenciales se obtendrán de las variables de entorno:

String bucketName = System.getenv("BUCKET_NAME");
String accessKey = System.getenv("S3_ACCESS_KEY_ID");
String secretKey = System.getenv("S3_SECRET_ACCESS_KEY");

Y dentro del método initializeAmazon(), puedes modificar la creación de las credenciales para usar las variables de entorno de la siguiente manera:

@PostConstruct
private void initializeAmazon() {
AwsBasicCredentials credentials = AwsBasicCredentials.create(
System.getenv("S3_ACCESS_KEY_ID"),
System.getenv("S3_SECRET_ACCESS_KEY")
);
this.s3client = S3Client.builder()
.region(Region.US_EAST_1)
.credentialsProvider(StaticCredentialsProvider.create(credentials))
.build();
}

Y la variable bucketName, ya no es necesario definirla, ya que ahora se obtiene de la variable de entorno:
private String bucketName = System.getenv("BUCKET_NAME");

2023-11-08 00:44 UTC, ezesafdie commented
> Todo esto en: src/main/java/com/company/service/BucketImageService.java
> 
> Como se setearon las variables de entorno en EC2:
> 
> En el código, puedes quitar las siguientes líneas, ya que ahora las credenciales se obtendrán de las variables de entorno:
> 
> String bucketName = System.getenv("BUCKET_NAME"); String accessKey = System.getenv("S3_ACCESS_KEY_ID"); String secretKey = System.getenv("S3_SECRET_ACCESS_KEY");
> 
> Y dentro del método initializeAmazon(), puedes modificar la creación de las credenciales para usar las variables de entorno de la siguiente manera:
> 
> @PostConstruct private void initializeAmazon() { AwsBasicCredentials credentials = AwsBasicCredentials.create( System.getenv("S3_ACCESS_KEY_ID"), System.getenv("S3_SECRET_ACCESS_KEY") ); this.s3client = S3Client.builder() .region(Region.US_EAST_1) .credentialsProvider(StaticCredentialsProvider.create(credentials)) .build(); }
> 
> Y la variable bucketName, ya no es necesario definirla, ya que ahora se obtiene de la variable de entorno: private String bucketName = System.getenv("BUCKET_NAME");

No entiendo a que te referis @celfiew, es lo mismo que ya tengo. O me estoy perdiendo de algo? 

Si para lo que decis es necesario sacar el pr del yml, capaz convenga sacar este antes y acutalizar ese pr para que no rompa

2023-11-08 03:29 UTC, celfiew commented
> > Todo esto en: src/main/java/com/company/service/BucketImageService.java
> > Como se setearon las variables de entorno en EC2:
> > En el código, puedes quitar las siguientes líneas, ya que ahora las credenciales se obtendrán de las variables de entorno:
> > String bucketName = System.getenv("BUCKET_NAME"); String accessKey = System.getenv("S3_ACCESS_KEY_ID"); String secretKey = System.getenv("S3_SECRET_ACCESS_KEY");
> > Y dentro del método initializeAmazon(), puedes modificar la creación de las credenciales para usar las variables de entorno de la siguiente manera:
> > @PostConstruct private void initializeAmazon() { AwsBasicCredentials credentials = AwsBasicCredentials.create( System.getenv("S3_ACCESS_KEY_ID"), System.getenv("S3_SECRET_ACCESS_KEY") ); this.s3client = S3Client.builder() .region(Region.US_EAST_1) .credentialsProvider(StaticCredentialsProvider.create(credentials)) .build(); }
> > Y la variable bucketName, ya no es necesario definirla, ya que ahora se obtiene de la variable de entorno: private String bucketName = System.getenv("BUCKET_NAME");
> 
> No entiendo a que te referis @celfiew, es lo mismo que ya tengo. O me estoy perdiendo de algo?
> 
> Si para lo que decis es necesario sacar el pr del yml, capaz convenga sacar este antes y acutalizar ese pr para que no rompa

Es que tengo una duda, tal cùal como esta el código debería ir a buscar el valor de las variables de entorno, verdad? Es decir si las variables de entorno ya estan configuradas en el EC2 el va y las busca de manera automatica, por esta razón es que no creo que sea necesario agregar nada en el .yml ya que las está leyedo directamente la información desde este código.

2023-11-08 04:55 UTC, nataliehelm commented
te deje un comentario. Me funcionó bien, si las observaciones de Cesar estan resueltas creo que ya se puede mergear

2023-11-08 23:19 UTC, celfiew commented
> > > Todo esto en: src/main/java/com/company/service/BucketImageService.java
> > > Como se setearon las variables de entorno en EC2:
> > > En el código, puedes quitar las siguientes líneas, ya que ahora las credenciales se obtendrán de las variables de entorno:
> > > String bucketName = System.getenv("BUCKET_NAME"); String accessKey = System.getenv("S3_ACCESS_KEY_ID"); String secretKey = System.getenv("S3_SECRET_ACCESS_KEY");
> > > Y dentro del método initializeAmazon(), puedes modificar la creación de las credenciales para usar las variables de entorno de la siguiente manera:
> > > @PostConstruct private void initializeAmazon() { AwsBasicCredentials credentials = AwsBasicCredentials.create( System.getenv("S3_ACCESS_KEY_ID"), System.getenv("S3_SECRET_ACCESS_KEY") ); this.s3client = S3Client.builder() .region(Region.US_EAST_1) .credentialsProvider(StaticCredentialsProvider.create(credentials)) .build(); }
> > > Y la variable bucketName, ya no es necesario definirla, ya que ahora se obtiene de la variable de entorno: private String bucketName = System.getenv("BUCKET_NAME");
> > 
> > 
> > No entiendo a que te referis @celfiew, es lo mismo que ya tengo. O me estoy perdiendo de algo?
> > Si para lo que decis es necesario sacar el pr del yml, capaz convenga sacar este antes y acutalizar ese pr para que no rompa
> 
> Es que tengo una duda, tal cùal como esta el código debería ir a buscar el valor de las variables de entorno, verdad? Es decir si las variables de entorno ya estan configuradas en el EC2 el va y las busca de manera automatica, por esta razón es que no creo que sea necesario agregar nada en el .yml ya que las está leyedo directamente la información desde este código.

Al final se setearon en el yml tendrías que usarlas, y tendrías que cambiar un poco la primera parte del código para que te quede algo así:

@Service
public class BucketImageService {

    private S3Client s3client;

    @Value("${bucketName}")
    private String bucketName;

    @Value("${accessKey}")
    private String accessKey;

    @Value("${secretKey}")
    private String secretKey;

    @Value("${endpointUrl}")
    private String endpointUrl;

    @PostConstruct
    private void initializeAmazon() {
        AwsBasicCredentials credentials = AwsBasicCredentials.create(this.accessKey, this.secretKey);
        this.s3client = S3Client.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(StaticCredentialsProvider.create(credentials))
                .build();
    }

2023-11-09 18:55 UTC, celfiew approved these changes, later dismissed
Nice!

2023-11-10 18:31 UTC, celfiew approved these changes

2023-11-10 20:17 UTC, merged