Feature/98 delete pet image
proyecto-final-dh/backend pull request #30
Opened 2023-11-05 23:55 UTC by stefany9229

- Se agrega a la entidad imagen el atributo mascota
- se agrega el metodo para eliminar una imagen del buckets3
-se agrega metodo en el ImageService para borrar una imagen de la BBDD de la tabla pet_images
- se ajustas los test findAll  y Save
- se agrega test para probar relanzamiento de Expecion en el BucketImageService

2023-11-05 23:58 UTC, stefany9229 commented
Se agrega a la entidad imagen el atributo mascota
se agrega el metodo para eliminar una imagen del buckets3
-se agrega metodo en el ImageService para borrar una imagen de la BBDD de la tabla pet_images
se ajustas los test findAll y Save
se agrega test para probar relanzamiento de Expecion en el BucketImageService

2023-11-07 22:36 UTC, celfiew requested changes

2023-11-07 22:36 UTC, celfiew commented on src/main/java/com/company/service/BucketImageService.java
Como se setearon las variables de entorno en EC2:

En el código, puedes quitar las siguientes líneas, ya que ahora las credenciales se obtendrán de las variables de entorno:

String bucketName = System.getenv("BUCKET_NAME");
String accessKey = System.getenv("S3_ACCESS_KEY_ID");
String secretKey = System.getenv("S3_SECRET_ACCESS_KEY");

Y dentro del método initializeAmazon(), puedes modificar la creación de las credenciales para usar las variables de entorno de la siguiente manera:

@PostConstruct
private void initializeAmazon() {
AwsBasicCredentials credentials = AwsBasicCredentials.create(
System.getenv("S3_ACCESS_KEY_ID"),
System.getenv("S3_SECRET_ACCESS_KEY")
);
this.s3client = S3Client.builder()
.region(Region.US_EAST_1)
.credentialsProvider(StaticCredentialsProvider.create(credentials))
.build();
}

Y la variable bucketName, ya no es necesario definirla, ya que ahora se obtiene de la variable de entorno:
private String bucketName = System.getenv("BUCKET_NAME");

2023-11-07 22:36 UTC, celfiew commented on WhatsApp Image 2023-10-06 at 7.28.48 AM.jpeg
Esto es para prueba o algo?:)

2023-12-03 22:24 UTC, closed without merging