Feature/9 crud pets
proyecto-final-dh/backend pull request #7
Opened 2023-10-24 22:57 UTC by javtr

2023-10-25 22:22 UTC, celfiew commented
Javi es posible que realices unos test y nos puedas facilitar los endpoints de postman para probar el CRUD? Si quieres te puedes guiar por el de Pet Species de Sofi que ella tiene la parte que te falta.

2023-10-27 02:34 UTC, javtr commented
* se responde el comentario anterior:
* se corrige el nombre de entidad
* se implementa el docker-compose
* se agregan test 
[pets.postman_collection.json](https://github.com/proyecto-final-dh/backend/files/13184437/pets.postman_collection.json)

2023-10-27 19:08 UTC, ezesafdie commented on src/main/java/com/company/controller/PetController.java
> +import org.springframework.web.bind.annotation.*;
No usemos el .* para los imports

2023-10-27 19:19 UTC, ezesafdie commented on src/main/java/com/company/model/entity/Pets.java
> +import lombok.*;
same

2023-10-27 19:24 UTC, ezesafdie commented on src/main/resources/02-data.sql
> +
Eliminemos comentarios si no tienen funcionalidad

2023-10-27 19:26 UTC, ezesafdie commented on src/main/resources/application.yml
> +
Lo mismo con estas lineas vacias. Intentemos no agregar archivos innecesarios al pr

2023-10-27 19:27 UTC, ezesafdie commented on pom.xml
> +		</dependency>
Ojo con las dependencias. Valida con develop porque estan repetidas

2023-10-27 19:38 UTC, ezesafdie commented on src/test/java/com/company/PetsTest/PetsTest.java
> +    }
Me fallan estos tests. Tené en cuenta que el contenedor se crea sin datos de mascotas

2023-10-27 19:45 UTC, ezesafdie requested changes
Revisemos las peticiones. Asi como las compartiste me tiran error porque esperan la columna "name1" en vez de "name". Esta bien que reciba "name" en vez de "name1", es lo que deberia pasar, pero hay que hacer el mapeo ahi

2023-10-27 23:47 UTC, javtr commented
* Corrección del uso de *
* Eliminación de comentarios
* Corrección de dependencias en el POM
* Corrección de test
* Archivo postman:
[pets.postman_collection02.json](https://github.com/proyecto-final-dh/backend/files/13193941/pets.postman_collection02.json)

2023-10-30 13:03 UTC, ezesafdie commented
Expando sobre mi comentario anterior.  Actualmente, al momento de crear (actualizar, etc) una mascota tenemos que pasar los siguientes datos:

```
{
    "name1": "Pip13",
    "status":"dead",
    "size": "small",
    "gender": "M",
    "description": "the best pet"
}
```

Deberia ser "name" en vez de name1, por mas que en la base de datos se guarde de esa manera. Es decir, como deberia quedar:

```
{
    "name": "Pip13",
    "status":"dead",
    "size": "small",
    "gender": "M",
    "description": "the best pet"
}
```

A su vez, las respuestas tambien deberian retornar el name (realmente tendriamos que corregir el name1 de la bd, es raro que esté asi, pero por el mientras hay que usar un dto para las respuestas y request)

Como pregunta extra, no estoy terminando de entender el tema de la paginación. O no funciona, o lo estoy usando mal (probablemente la segunda). Si yo le pego directamente al siguiente curl:
```
curl --location 'localhost:8080/pets'
```
funciona sin problema, pero en cuanto agrego la paginacion no me retorna nada:
```
curl --location 'localhost:8080/pets?page=1&size=2'
```

2023-10-30 13:08 UTC, ezesafdie commented
Como comentario extra, el tema de la validación por nombre al momento de crear y actualizar una mascota, no creo que haya que hacerlo. Seguramente existan mascotas con el mismo nombre

2023-11-01 00:16 UTC, ezesafdie approved these changes

2023-11-01 00:27 UTC, celfiew approved these changes

2023-11-01 02:20 UTC, merged